controlpanel/controlpanel/urls.py
# controlpanel/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from finncasino import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^finncasino/',include('finncasino.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

controlpanel/finncasino/urls.py
# finncasino/urls.py
from django.conf.urls import url
from finncasino import views
app_name = 'finncasino'

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^events/$',views.events,name='events'),
    url(r'^events/(?P<event_id>\d+)/$',views.events,name='events'),
]

controlpanel/finncasino/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
from django.db.models import CharField, DateTimeField, Model, FloatField


def __str__(self):
  return self.user.username

class Event(Model):
  name = CharField(max_length=255)
  participantA = CharField(max_length=255)
  participantB = CharField(max_length=255)
  start = DateTimeField()
  end = DateTimeField()
  oddToWin =  FloatField(validators=[MinValueValidator(1.0), MaxValueValidator(50)])
  oddToLose =  FloatField(validators=[MinValueValidator(1.0), MaxValueValidator(50)])
  oddToDraw =  FloatField(validators=[MinValueValidator(1.0), MaxValueValidator(50)])
  created = DateTimeField(auto_now_add=True)
  modified = DateTimeField(auto_now=True)

controlpanel/finncasino/forms.py
# finncasino/forms.py
from django import forms
from django.contrib.auth.models import User

from finncasino.models import Event
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')


class EventForm(forms.ModelForm):
    start = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
    end = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])

    class Meta():
        model = Event
        fields = ('name', 'participantA', 'participantB', 'start','end','oddToWin','oddToLose','oddToDraw')

controlpanel/finncasino/views.py
# finncasino/views.py
import datetime
from django.shortcuts import render
from finncasino.forms import EventForm, UserForm
from finncasino.models import Event
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

def index(request):
    return render(request,'finncasino/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    context = {
        "error": "",
        "registered": False
    }

    if request.method == 'POST':
        context["user_form"] = UserForm(data=request.POST)
        if context["user_form"].is_valid():
            user = context["user_form"].save()
            user.set_password(user.password)
            user.save()
            context["registered"] = True
        else:
            context["error"] = context["user_form"].errors
    else:
        context["user_form"] = UserForm()
    return render(request,'finncasino/registration.html',context)

def user_login(request):
    User = get_user_model()

    context = {
        "error": ""
    }
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                context["error"] = "Your account is inactive."
        else:
            context["error"]="Invalid credentials"
            return render(request, 'finncasino/login.html', context)
    else:
        return render(request, 'finncasino/login.html', context)

@login_required
def events(request, event_id=None):
    context = {
        "events": Event.objects.all()
    }

    if request.method == 'POST':
        return handle_post(context, request, event_id)

    elif request.method == 'DELETE' and event_id != None:
        return handle_delete(context, request, event_id)

    elif request.method == 'GET':
        return handle_get(context, request, event_id)

    else:
        return handle_unsupported(request)


# POST
def handle_post(context, request, event_id):
    context["event_form"] = EventForm(data=request.POST)

    if context["event_form"].is_valid():
        event = context["event_form"].save(commit=False)

        Event.objects.update_or_create(
            id=event_id,
            defaults={
                'name': event.name,
                'participantA': event.participantA,
                'participantB': event.participantB,
                'start': event.start,
                'end': event.end,
                'oddToWin': event.oddToWin,
                'oddToLose': event.oddToLose,
                'oddToDraw': event.oddToDraw
            }
        )
    else:
        context["error"] = context["event_form"].errors

    if event_id is None:
        return render(request, 'finncasino/events.html', context)
    else:
        return render_event(context, request, event_id)


# DELETE
def handle_delete(context, request, event_id):
    context["event_form"] = EventForm()
    Event.objects.get(id=event_id).delete()

    return render(request, 'finncasino/events.html', context)


# GET
def handle_get(context, request, event_id):
    context["event_form"] = EventForm()

    if event_id is None:
        return render(request, 'finncasino/events.html', context)
    else:
        return render_event(context, request, event_id)


# UNSUPPORTED
def handle_unsupported(request):
    return render(request, 'finncasino/error.html')


# GENERIC
def render_event(context, request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    event.start = event.start.strftime('%d/%m/%Y %H:%M')
    event.end = event.end.strftime('%d/%m/%Y %H:%M')

    context["event_form"] = EventForm(instance=event)

    event = get_object_or_404(Event, pk=event_id)
    context["event"] = event

    return render(request, 'finncasino/event.html', context)

controlpanel/templates/finncasino/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "finncasino.css" %}">
  </head>
  <body>
    <img class="logo" src="{% static "finncasino.png" %}">
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav d-flex" style="flex-direction: row; align-items: center;">
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a class="navbar-link pr-3" href="{% url 'finncasino:events' %}">Events</a></li>     
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link pr-3" href="{% url 'finncasino:register' %}">Register</a></li>     
            <li><a class="navbar-link" href="{% url 'finncasino:user_login' %}">Login</a></li>
          {% endif %}
      </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

controlpanel/templates/finncasino/error.html
{% extends "finncasino/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron mt-4">
        <h2>Welcome to the FinnCasino control panel!</h2>
        <h3>This type of request is not supported!</h3>
  </div>
</div>
{% endblock %}

controlpanel/templates/finncasino/event.html
{% extends "finncasino/base.html" %}
{% block body_block %}
{{ form.date }}

<script>
  $(function () {
    $("#id_start").datetimepicker({
      format: 'd/m/Y H:i',
    });
    $("#id_end").datetimepicker({
      format: 'd/m/Y H:i',
    });
  });

  document.addEventListener('DOMContentLoaded', function() {
    startValue = $("input[name='start']")[0].value;
    endValue = $("input[name='start']")[0].value;
  }, false);
</script>
<div class="container">
  <div class="jumbotron mt-4">
    <div class="row">
        <div class="col-xl-4 text-center">
            <h3>Name of the event</h3>
        </div>
        <div class="col-xl-4 text-center">
            <h3>Starts at</h3>
        </div>
        <div class="col-xl-4 text-center">
            <h3>Ends at</h3>
        </div>
    </div>
    <div class="event-parent" data-id={{ event.id }}>
      <hr>
      <div class="row">
          <div class="col-xl-4 text-center">
              {{ event.name }}
          </div>
          <div class="col-xl-4 text-center">
              {{ event.start }}
          </div>
          <div class="col-xl-4 text-center">
              {{ event.end }}
          </div>
        </div>
        <div class="row">
          <div class="col-xl-4 text-center">
              {{ event.oddToWin }} ({{ event.participantA}})
          </div>
          <div class="col-xl-4 text-center">
              {{ event.oddToLose }} (Draw)
          </div>
          <div class="col-xl-4 text-center">
              {{ event.oddToDraw }} ({{ event.participantB}})
          </div>
        </div>
      </div>
      <form class="pt-5" enctype="multipart/form-data" method="POST" onload="changeDateTimeFormat()">
        {% csrf_token %}
        {{ event_form.as_p }}
        {% if event_form %}
          <input type="submit" name="" value="Update current event">
        {% endif %}
      </form>
  </div>
</div>
{% endblock %}

controlpanel/templates/finncasino/events.html
{% extends "finncasino/base.html" %}
{% block body_block %}
{{ form.date }}

<script>
  $(function () {
    $("#id_start").datetimepicker({
      format: 'd/m/Y H:i',
    });
    $("#id_end").datetimepicker({
      format: 'd/m/Y H:i',
    });
  });

  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

  function deleteEvent(id) {
    $.ajax({
    url: window.location.href + id,
    type: 'DELETE',
    beforeSend:     function (request) {
      request.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
    },
    data: {
      csrfmiddlewaretoken: getCookie('csrftoken')
    },
    success: function(result) {
      $("div[data-id='" + id + "']").remove();
      if($('.event-parent').length < 1) {
        window.location.href = window.location.href;
      }
    },
    error: function(request,msg,error) {
        // handle failure
    }
  })}
</script>
<div class="container">
  <div class="jumbotron mt-4">
    {% if not events %}
      <h2>No events</h2>
    {% else %}
    <div class="row">
        <div class="col-xl-3 text-center">
            <h3>Name of the event</h3>
        </div>
        <div class="col-xl-3 text-center">
            <h3>Starts at</h3>
        </div>
        <div class="col-xl-3 text-center">
            <h3>Ends at</h3>
        </div>
    </div>
    {% endif %}
    {% for event in events %}
    <div class="event-parent" data-id={{ event.id }}>
      <hr>
      <div class="row">
          <div class="col-xl-3 text-center">
              {{ event.name }}
          </div>
          <div class="col-xl-3 text-center">
              {{ event.start }}
          </div>
          <div class="col-xl-3 text-center">
              {{ event.end }}
          </div>
          <div class="col-xl-3 text-center">
              <button class="btn-primary" onclick="window.location.href=window.location.href + '{{ event.id }}'">
                Edit
              </button>
          </div>
        </div>
        <div class="row">
          <div class="col-xl-3 text-center">
              {{ event.oddToWin }} ({{ event.participantA}})
          </div>
          <div class="col-xl-3 text-center">
              {{ event.oddToLose }} (Draw)
          </div>
          <div class="col-xl-3 text-center">
              {{ event.oddToDraw }} ({{ event.participantB}})
          </div>
          <div class="col-xl-3 text-center">
              <button class="btn-danger" onclick="deleteEvent({{ event.id}})">
                  Delete
              </button>
          </div>
        </div>
      </div>
    {% endfor %}
    <form class="pt-5" enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{ event_form.as_p }}
      {% if event_form %}
        <input type="submit" name="" value="Create new event">
      {% endif %}
    </form>
  </div>
</div>
{% endblock %}

controlpanel/templates/finncasino/index.html
{% extends "finncasino/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron mt-4">
    {% if user.is_authenticated %}
        <h3>Hello {{ user.username }}</h3>
    {% else %}
    <h2>Welcome to the FinnCasino control panel !</h2>
        <h3>Please login to access the events</h3>
    {% endif %}
  </div>
</div>
{% endblock %}

controlpanel/templates/finncasino/login.html
{% extends 'finncasino/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron mt-4">
      <h2 class="pb-3">Login here :</h2>
        <form method="post" action="{% url 'finncasino:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
          <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
          <input type="submit" name="" value="Login">
        </form>
        {% if error %}
          <div class="alert alert-danger" role="alert">
              {{ error }}
          </div>
        {% endif %}
  </div>
</div>
{% endblock %}

controlpanel/templates/finncasino/registration.html
{% extends "finncasino/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron mt-4">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {% if user_form %}
            <input type="submit" name="" value="Register">
          {% endif %}
        </form>
      {% endif %}
      {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
      {% endif %}
    </div>
    
  </div>
{% endblock %}